"""Phase 3 Stage 3-D: Waymax-native forward vehicle model.

EXACT forward equation, quoted VERBATIM (not paraphrased) from the
installed Waymax source at
``waymax/dynamics/bicycle_model.py``,
``InvertibleBicycleModel.compute_update`` docstring and body (read
fresh for this stage, revision ``a64dfec9be8576b60d9cecc94f406d9812d4a7d0``
per ``docs/phase3/OVERNIGHT_PROGRESS.md``):

    Forward dynamics:
      new_x = x + vel_x * t + 1/2 * accel * cos(yaw) * t ** 2
      new_y = y + vel_y * t + 1/2 * accel * sin(yaw) * t ** 2
      new_yaw = yaw + steering * (speed * t + 1/2 * accel * t ** 2)
      new_vel = vel + accel * t

And the body, verbatim (variable names as in the installed source):

    x = trajectory.x
    y = trajectory.y
    vel_x = trajectory.vel_x
    vel_y = trajectory.vel_y
    yaw = trajectory.yaw
    speed = jnp.sqrt(trajectory.vel_x**2 + trajectory.vel_y**2)

    accel, steering = <clipped action components>
    t = self._dt

    new_x = x + vel_x * t + 0.5 * accel * jnp.cos(yaw) * t**2
    new_y = y + vel_y * t + 0.5 * accel * jnp.sin(yaw) * t**2
    delta_yaw = steering * (speed * t + 0.5 * accel * t**2)
    new_yaw = geometry.wrap_yaws(yaw + delta_yaw)
    new_vel = speed + accel * t
    new_vel_x = new_vel * jnp.cos(new_yaw)
    new_vel_y = new_vel * jnp.sin(new_yaw)

Two details matter for exact reproduction:

  1. ``vel_x``/``vel_y`` at the START of the step are recomputed by
     Waymax from ``speed = sqrt(vel_x**2 + vel_y**2)`` and ``yaw``
     is NOT re-derived from ``vel_x``/``vel_y`` for the *current*
     step -- position update uses the trajectory's OWN ``vel_x``/
     ``vel_y`` fields directly (``x + vel_x*t + ...``), not
     ``speed*cos(yaw)``. In this repo's own controller state
     (``ControllerState``: x, y, yaw, speed -- no separate vel_x/
     vel_y), ``vel_x``/``vel_y`` are reconstructed as
     ``speed*cos(yaw)``/``speed*sin(yaw)`` before applying the
     update -- i.e. this module assumes the incoming ``speed``/
     ``yaw`` are already mutually consistent with vel_x/vel_y (true
     by construction here, since ``ControllerState`` has no
     independent heading-of-travel field distinct from ``yaw``, and
     every state this module ever produces is generated by this same
     model, so the invariant self-propagates). This is the ONLY place
     this module's state representation is a strict subset of
     Waymax's own ``Trajectory`` (which stores vel_x/vel_y and yaw as
     independently-settable fields); the model-equivalence test below
     verifies this reconstruction reproduces Waymax bit-for-bit
     because Waymax's own OUTPUT also re-derives
     ``new_vel_x = new_vel*cos(new_yaw)``, ``new_vel_y =
     new_vel*sin(new_yaw)`` at the end of every step, so the two
     representations stay exactly consistent step over step.
  2. ``new_vel = speed + accel*t`` where ``speed = sqrt(vel_x**2 +
     vel_y**2)`` -- i.e. always non-negative before update (a
     Euclidean norm), so ``new_vel`` can go negative if ``accel*t``
     is a large enough negative number relative to ``speed``; Waymax
     does not clamp ``new_vel`` at zero. This module reproduces that
     exactly (no artificial floor at 0) -- see
     ``tests/control/test_vehicle_model.py`` for a case validating
     this against the real installed Waymax dynamics model directly.

No wheelbase parameter exists anywhere in this equation (unlike
ASMC's ``tan(delta)``-based Ackermann model) -- steering curvature
multiplies a speed/accel-dependent arc-length term directly. This
module's one-step update function computes EXACTLY this equation, at
dt=0.1s (Stage 3-0 locked decision #2), with no inner faster loop and
no reinterpretation.
"""

import numpy as np

from src.control.mpc_types import (
    MAX_ACCEL_MPS2,
    MAX_STEERING_CURVATURE,
    MPC_DT_S,
)


def _wrap_yaw(yaw: np.ndarray) -> np.ndarray:
    """Matches Waymax's ``geometry.wrap_yaws``: wraps to (-pi, pi]."""

    return (yaw + np.pi) % (2.0 * np.pi) - np.pi


def clip_command(accel: float, steering: float) -> tuple:
    """Clips a raw command to Waymax's own action bounds -- mirrors
    ``InvertibleBicycleModel._clip_values`` exactly (element-wise clip
    to [-max_accel, max_accel] / [-max_steering, max_steering])."""

    accel_clipped = float(np.clip(accel, -MAX_ACCEL_MPS2, MAX_ACCEL_MPS2))
    steering_clipped = float(np.clip(steering, -MAX_STEERING_CURVATURE, MAX_STEERING_CURVATURE))
    return accel_clipped, steering_clipped


def step(
    state: np.ndarray,
    control: np.ndarray,
    dt: float = MPC_DT_S,
    clip_control: bool = True,
) -> np.ndarray:
    """One-step Waymax-native forward update.

    Args:
        state: array-like ``[x, y, yaw, speed]`` (shape (4,), or any
            leading batch shape (..., 4) -- pure numpy, broadcasts
            like the equations above).
        control: array-like ``[accel, steering_curvature]`` (shape
            (2,) or (..., 2)).
        dt: time step (s). Defaults to the locked MPC dt (0.1s,
            matching Waymax's own simulation dt 1:1).
        clip_control: if True (default, matching
            ``InvertibleBicycleModel``'s own always-on internal
            clipping), the control is clipped to the box bounds
            BEFORE being applied -- i.e. this function reproduces
            Waymax's actual behavior of silently clipping out-of-range
            actions, not merely accepting only in-range ones. Callers
            that already guarantee in-range commands (e.g. the MPC
            solver itself, which enforces bounds via the optimizer)
            may pass False to skip the redundant clip.

    Returns:
        Next state, same shape as ``state``: ``[new_x, new_y,
        new_yaw, new_speed]``.
    """

    state = np.asarray(state, dtype=np.float64)
    control = np.asarray(control, dtype=np.float64)

    x = state[..., 0]
    y = state[..., 1]
    yaw = state[..., 2]
    speed = state[..., 3]

    accel = control[..., 0]
    steering = control[..., 1]
    if clip_control:
        accel = np.clip(accel, -MAX_ACCEL_MPS2, MAX_ACCEL_MPS2)
        steering = np.clip(steering, -MAX_STEERING_CURVATURE, MAX_STEERING_CURVATURE)

    # vel_x/vel_y reconstructed from (speed, yaw) -- see module
    # docstring point 1: valid because this module's own state always
    # keeps speed/yaw self-consistent with vel_x/vel_y across steps.
    vel_x = speed * np.cos(yaw)
    vel_y = speed * np.sin(yaw)

    t = dt
    new_x = x + vel_x * t + 0.5 * accel * np.cos(yaw) * t**2
    new_y = y + vel_y * t + 0.5 * accel * np.sin(yaw) * t**2
    delta_yaw = steering * (speed * t + 0.5 * accel * t**2)
    new_yaw = _wrap_yaw(yaw + delta_yaw)
    new_speed = speed + accel * t  # no floor at 0 -- matches Waymax exactly.

    return np.stack([new_x, new_y, new_yaw, new_speed], axis=-1)
