"""Stage 3-D: LTV-MPC solve-loop tests.

Covers the required synthetic tracking scenarios (straight, arcs,
offsets, speed changes), control saturation, non-finite rejection,
warm-start behavior, and reset behavior -- see the task brief's
"Required tests" list. All scenarios track a HAND-BUILT reference
(this stage does not wire into Stage 3-C's planner output -- that is
Stage 3-E).
"""

import numpy as np
import pytest

from src.control import vehicle_model
from src.control.ltv_mpc import LtvMpcController, MpcConfig, load_mpc_config
from src.control.mpc_cost import CostWeights
from src.control.mpc_types import (
    MAX_ACCEL_MPS2,
    MAX_STEERING_CURVATURE,
    MPC_DT_S,
    ControllerState,
    ControllerStatus,
    ReferencePoint,
)

HORIZON = 20


def make_config(horizon=HORIZON, max_iterations=200):
    weights = CostWeights(
        w_pos=10.0, w_yaw=5.0, w_speed=2.0,
        w_accel_effort=0.05, w_steering_effort=0.05,
        w_accel_rate=0.1, w_steering_rate=0.1,
        w_terminal_pos=20.0, w_terminal_yaw=10.0, w_terminal_speed=5.0,
    )
    return MpcConfig(horizon=horizon, dt_s=MPC_DT_S, weights=weights, max_iterations=max_iterations)


def straight_reference(start_x, start_y, yaw, speed, horizon, dt):
    """Constant-speed, constant-heading straight-line reference."""

    ref = []
    x, y = start_x, start_y
    for _ in range(horizon):
        x += speed * np.cos(yaw) * dt
        y += speed * np.sin(yaw) * dt
        ref.append(ReferencePoint(x=x, y=y, yaw=yaw, speed=speed))
    return ref


def speed_profile_reference(start_x, start_y, yaw, start_speed, accel, horizon, dt):
    """Constant-heading, constant-acceleration reference (used for
    both the speed-increase and speed-decrease tests)."""

    ref = []
    x, y = start_x, start_y
    speed = start_speed
    for _ in range(horizon):
        x += speed * np.cos(yaw) * dt + 0.5 * accel * np.cos(yaw) * dt**2
        y += speed * np.sin(yaw) * dt + 0.5 * accel * np.sin(yaw) * dt**2
        speed += accel * dt
        ref.append(ReferencePoint(x=x, y=y, yaw=yaw, speed=speed))
    return ref


def arc_reference(start_x, start_y, yaw, speed, curvature, horizon, dt):
    """Constant-speed, constant-curvature arc reference (generated by
    forward-simulating vehicle_model.step with a constant steering
    command at zero acceleration -- an exact, self-consistent arc
    under this same forward model)."""

    state = np.array([start_x, start_y, yaw, speed])
    control = np.array([0.0, curvature])
    ref = []
    for _ in range(horizon):
        state = vehicle_model.step(state, control, dt=dt, clip_control=False)
        ref.append(ReferencePoint(x=state[0], y=state[1], yaw=state[2], speed=state[3]))
    return ref


def run_to_convergence(controller, state, reference_fn, steps=40):
    """Repeatedly solves + advances the true nonlinear state one MPC
    step at a time (closed loop), regenerating the reference horizon
    fresh each step relative to the CURRENT state's own forward arc.
    Returns the list of states visited."""

    trajectory = [state]
    for _ in range(steps):
        reference = reference_fn(state)
        result = controller.solve(state, reference)
        assert result.status == ControllerStatus.OK, result.error
        command = result.command.as_array()
        next_state_arr = vehicle_model.step(state.as_array(), command, dt=MPC_DT_S, clip_control=True)
        state = ControllerState.from_array(next_state_arr)
        trajectory.append(state)
    return trajectory


# ----------------------------------------------------------------------
# Tracking scenarios
# ----------------------------------------------------------------------


def test_straight_constant_speed_tracking():
    config = make_config()
    controller = LtvMpcController(config)
    target_speed = 15.0

    # Fixed lane at y=0 (NOT re-anchored to the current state's own y
    # each call) -- this is what actually exercises "converge to and
    # hold the reference," since a reference that re-anchors to
    # wherever the vehicle currently is would never ask it to correct
    # an initial lateral offset.
    def reference_fn(state):
        return straight_reference(state.x, 0.0, 0.0, target_speed, HORIZON, MPC_DT_S)

    state = ControllerState(x=0.0, y=2.0, yaw=0.05, speed=10.0)  # slight offset + speed gap
    trajectory = run_to_convergence(controller, state, reference_fn, steps=40)

    final = trajectory[-1]
    assert abs(final.speed - target_speed) < 1.0
    assert abs(final.yaw) < 0.1
    assert abs(final.y) < 1.0


def test_speed_increase_tracking():
    config = make_config()
    controller = LtvMpcController(config)

    def reference_fn(state):
        return speed_profile_reference(state.x, state.y, 0.0, state.speed, accel=2.0, horizon=HORIZON, dt=MPC_DT_S)

    state = ControllerState(x=0.0, y=0.0, yaw=0.0, speed=5.0)
    trajectory = run_to_convergence(controller, state, reference_fn, steps=30)

    speeds = [s.speed for s in trajectory]
    assert speeds[-1] > speeds[0] + 5.0  # meaningfully accelerated


def test_speed_decrease_tracking():
    config = make_config()
    controller = LtvMpcController(config)

    def reference_fn(state):
        return speed_profile_reference(state.x, state.y, 0.0, state.speed, accel=-2.0, horizon=HORIZON, dt=MPC_DT_S)

    state = ControllerState(x=0.0, y=0.0, yaw=0.0, speed=15.0)
    trajectory = run_to_convergence(controller, state, reference_fn, steps=30)

    speeds = [s.speed for s in trajectory]
    assert speeds[-1] < speeds[0] - 5.0  # meaningfully decelerated


def test_constant_curvature_left_arc_tracking():
    config = make_config()
    controller = LtvMpcController(config)
    curvature = 0.05  # positive = left turn (new_yaw = yaw + steering*k, k>0)

    def reference_fn(state):
        return arc_reference(state.x, state.y, state.yaw, 10.0, curvature, HORIZON, MPC_DT_S)

    state = ControllerState(x=0.0, y=0.0, yaw=0.0, speed=10.0)
    trajectory = run_to_convergence(controller, state, reference_fn, steps=40)

    # A left arc should produce a monotonically increasing yaw trend.
    yaws = [s.yaw for s in trajectory]
    assert yaws[-1] > yaws[0]


def test_constant_curvature_right_arc_tracking():
    config = make_config()
    controller = LtvMpcController(config)
    curvature = -0.05  # negative = right turn

    def reference_fn(state):
        return arc_reference(state.x, state.y, state.yaw, 10.0, curvature, HORIZON, MPC_DT_S)

    state = ControllerState(x=0.0, y=0.0, yaw=0.0, speed=10.0)
    trajectory = run_to_convergence(controller, state, reference_fn, steps=40)

    yaws = [s.yaw for s in trajectory]
    assert yaws[-1] < yaws[0]


def test_initial_lateral_offset_converges():
    config = make_config()
    controller = LtvMpcController(config)
    target_speed = 10.0

    def reference_fn(state):
        return straight_reference(state.x, 0.0, 0.0, target_speed, HORIZON, MPC_DT_S)

    state = ControllerState(x=0.0, y=5.0, yaw=0.0, speed=target_speed)
    trajectory = run_to_convergence(controller, state, reference_fn, steps=50)

    ys = [abs(s.y) for s in trajectory]
    assert ys[-1] < ys[0]
    assert ys[-1] < 1.0


def test_initial_heading_offset_converges():
    config = make_config()
    controller = LtvMpcController(config)
    target_speed = 10.0

    def reference_fn(state):
        return straight_reference(state.x, state.y, 0.0, target_speed, HORIZON, MPC_DT_S)

    state = ControllerState(x=0.0, y=0.0, yaw=0.3, speed=target_speed)
    trajectory = run_to_convergence(controller, state, reference_fn, steps=40)

    yaws = [abs(s.yaw) for s in trajectory]
    assert yaws[-1] < yaws[0]
    assert yaws[-1] < 0.05


# ----------------------------------------------------------------------
# Saturation / robustness
# ----------------------------------------------------------------------


def test_control_saturation_clips_to_bounds():
    """A reference requiring far more accel/steering than the box
    bounds allow must produce a command clipped to bounds, not one
    silently exceeding them."""

    config = make_config()
    controller = LtvMpcController(config)

    # Reference far ahead and to the side, demanding an enormous
    # speed/heading change within one horizon -- forces saturation.
    reference = [
        ReferencePoint(x=1000.0 * (i + 1), y=500.0 * (i + 1), yaw=1.5, speed=100.0)
        for i in range(HORIZON)
    ]
    state = ControllerState(x=0.0, y=0.0, yaw=0.0, speed=0.0)
    result = controller.solve(state, reference)

    assert result.status == ControllerStatus.OK
    assert abs(result.command.acceleration_mps2) <= MAX_ACCEL_MPS2 + 1e-9
    assert abs(result.command.steering_curvature) <= MAX_STEERING_CURVATURE + 1e-9
    assert np.all(np.abs(result.horizon_commands[:, 0]) <= MAX_ACCEL_MPS2 + 1e-9)
    assert np.all(np.abs(result.horizon_commands[:, 1]) <= MAX_STEERING_CURVATURE + 1e-9)
    # Given the extreme reference, saturation should actually bind.
    assert np.any(np.isclose(np.abs(result.horizon_commands[:, 0]), MAX_ACCEL_MPS2, atol=1e-3))


def test_nonfinite_state_rejected():
    config = make_config()
    controller = LtvMpcController(config)
    reference = straight_reference(0.0, 0.0, 0.0, 10.0, HORIZON, MPC_DT_S)

    bad_state = ControllerState(x=float("nan"), y=0.0, yaw=0.0, speed=10.0)
    result = controller.solve(bad_state, reference)
    assert result.status == ControllerStatus.INVALID_INPUT
    assert result.command is None


def test_nonfinite_reference_rejected():
    config = make_config()
    controller = LtvMpcController(config)
    state = ControllerState(x=0.0, y=0.0, yaw=0.0, speed=10.0)

    reference = straight_reference(0.0, 0.0, 0.0, 10.0, HORIZON, MPC_DT_S)
    reference[3] = ReferencePoint(x=float("inf"), y=0.0, yaw=0.0, speed=10.0)

    result = controller.solve(state, reference)
    assert result.status == ControllerStatus.INVALID_INPUT
    assert result.command is None


# ----------------------------------------------------------------------
# Warm-start / reset
# ----------------------------------------------------------------------


def test_warm_start_no_worse_than_cold_start():
    """A second consecutive solve using the warm-started previous
    solution should not produce a worse (higher) FIRST-iterate cost
    than an independent cold-start solve on the same problem --
    measured here as: the warm-started solve's final cost is <= the
    cold-start solve's final cost (both given the same iteration
    budget), since warm-starting from a near-optimal previous solution
    should already be close to optimal for a slowly-changing
    continuing trajectory.
    """

    config = make_config(max_iterations=50)
    controller_warm = LtvMpcController(config)
    controller_cold = LtvMpcController(config)

    target_speed = 12.0
    state = ControllerState(x=0.0, y=1.0, yaw=0.02, speed=10.0)
    reference = straight_reference(state.x, state.y, 0.0, target_speed, HORIZON, MPC_DT_S)

    # First solve seeds controller_warm's warm-start.
    first_result = controller_warm.solve(state, reference)
    assert first_result.status == ControllerStatus.OK

    # Advance state one step under the first solved command (both
    # controllers see the same next state/reference).
    next_state_arr = vehicle_model.step(
        state.as_array(), first_result.command.as_array(), dt=MPC_DT_S, clip_control=True
    )
    next_state = ControllerState.from_array(next_state_arr)
    next_reference = straight_reference(next_state.x, next_state.y, 0.0, target_speed, HORIZON, MPC_DT_S)

    warm_result = controller_warm.solve(next_state, next_reference)
    cold_result = controller_cold.solve(next_state, next_reference)

    assert warm_result.status == ControllerStatus.OK
    assert cold_result.status == ControllerStatus.OK
    # Warm start should reach at least as good a cost (small tolerance
    # for solver noise/non-convexity of the underlying nonlinear
    # rollout).
    assert warm_result.cost <= cold_result.cost + 1e-3


def test_reset_clears_warm_start_state():
    config = make_config()
    controller = LtvMpcController(config)
    state = ControllerState(x=0.0, y=1.0, yaw=0.02, speed=10.0)
    reference = straight_reference(state.x, state.y, 0.0, 12.0, HORIZON, MPC_DT_S)

    result1 = controller.solve(state, reference)
    assert result1.status == ControllerStatus.OK
    assert controller._warm_start is not None

    controller.reset()
    assert controller._warm_start is None
    assert controller._previous_command is None

    # After reset, a fresh solve should use the default (zero) initial
    # guess, exactly like a brand-new controller instance would.
    fresh_controller = LtvMpcController(config)
    result_after_reset = controller.solve(state, reference)
    result_fresh = fresh_controller.solve(state, reference)
    assert result_after_reset.status == ControllerStatus.OK
    assert result_fresh.status == ControllerStatus.OK
    np.testing.assert_allclose(
        result_after_reset.horizon_commands, result_fresh.horizon_commands, atol=1e-6
    )


def test_load_mpc_config_reads_new_additive_section():
    config = load_mpc_config()
    assert config.horizon > 0
    assert config.dt_s == pytest.approx(MPC_DT_S)
    assert config.weights.w_pos > 0
